### ISSUE TITLE
Width is incorrect in iOS

### ISSUE THREAD

**Issue by robert-j-webb** [html-next/flexi-layouts#23]
Hello!

I'm using the iOS simulator right now and I was trying to figure out why my iPhone 6+ was refusing to show the mobile view of my app as it should. Eventually I realized that my usage of the LayoutService was correct, but that it was returning the incorrect values, just on iOS.

For some reason related to mobile iOS, this code

```js
    _currentWidth: function _currentWidth() {
      return Math.max(document.documentElement.clientWidth, window.innerWidth || 0);
    },
```

Returns 980 instead of 414 when initialized. I put a break point into it and looked closer and I got these results:

```js
document.documentElement.clientWidth === 980 //true
window.innerWidth === 414 //true
```

However, I have my own computed property like this (just in my component code):

```js
  isMobile: computed('responsive.isMobile', function(){
    const width = Math.max(document.documentElement.clientWidth, window.innerWidth || 0)
    return width < 600;
  }),
```

which returns the correct value (true). 

I did not test this on a real phone, but it's quite possible that it has the same problem or it might be a simulator only issue. ~~Could I make a PR to use `Math.min` for both `_currentWidth` and `_currentHeight`? Or is there a pressing reason for using `Math.max`?~~

My solution ended up being this in the component, so it appears to be a timing issue.
```js
  didRender() {
      this.LayoutService.trigger('width-changed');
  },
```

**Comment by RobbieTheWagner** [comment]
Hi @robert-j-webb any ideas on a fix we can include in flexi?

**Comment by robert-j-webb** [comment]
Well, I don't know what possible side effects this has, but you could set up a `schedule('afterRender', updateResize)` in your init function for the service.

**Comment by robert-j-webb** [comment]
Hey I think I found another answer that might work better. It turns out that `screen.width` is consistent in iOS whereas `window.innerWidth` changes quite a bit.
https://stackoverflow.com/questions/4629969/ios-return-bad-value-for-window-innerheight-width

I don't think there are any issues with other browsers but I'm not quite certain.

**Comment by RobbieTheWagner** [comment]
I'm open to whatever works.

**Comment by robert-j-webb** [comment]
Ok I'll write a PR and see what others say. I'll try to make the logic such that it chooses between all 3 equally
